@API_HostAddress = http://localhost:5126/api
@Mobile_Otp = "7601"
@Email_Otp = "3278"

POST {{API_HostAddress}}/auth/register-user
Content-Type: application/json
Accept: application/json

{
  "name": "name",
  "icNumber": "123456789",
  "mobile": "+995512345678",
  "email": "test@gmail.com"
}
###

POST {{API_HostAddress}}/auth/send-mobile-otp
Content-Type: application/json
Accept: application/json

{
  "icNumber": "123456789",
  "deviceId": "deviceId1"
}
###

POST {{API_HostAddress}}/auth/verify-mobile-otp
Content-Type: application/json
Accept: application/json

{
  "icNumber": "123456789",
  "otpPin": {{Mobile_Otp}}
}
###

POST {{API_HostAddress}}/auth/send-email-otp
Content-Type: application/json
Accept: application/json

{
  "icNumber": "123456789",
  "deviceId": "deviceId1"
}
###

POST {{API_HostAddress}}/auth/verify-email-otp
Content-Type: application/json
Accept: application/json

{
  "icNumber": "123456789",
  "otpPin": {{Email_Otp}}
}
###

POST {{API_HostAddress}}/auth/accept-privacy-policy
Content-Type: application/json
Accept: application/json

{
  "icNumber": "123456789"
}
###

POST {{API_HostAddress}}/auth/register-device
Content-Type: application/json
Accept: application/json

{
  "icNumber": "123456789",
  "deviceId": "deviceId1",
  "pin": "1234"
}
###

GET {{API_HostAddress}}/user/
Accept: application/json
###

GET {{API_HostAddress}}/device/
Accept: application/json
###